### ISSUE TITLE
can't run example

### ISSUE THREAD

**Issue by ChenYCL** [zyra/ionic2-super-tabs-example#15]
Runtime Error
Uncaught (in promise): TypeError: navContainer.parent.getAllChildNavs is not a function TypeError: navContainer.parent.getAllChildNavs is not a function at UrlSerializer._createSegment (http://localhost:8100/build/vendor.js:42606:81) at UrlSerializer.serializeComponent (http://localhost:8100/build/vendor.js:42569:29) at DeepLinker.getSegmentFromNav (http://localhost:8100/build/vendor.js:20749:33) at DeepLinker.getSegmentsFromNav (http://localhost:8100/build/vendor.js:20725:32) at http://localhost:8100/build/vendor.js:20731:46 at Array.forEach (<anonymous>) at DeepLinker.getSegmentsFromNav (http://localhost:8100/build/vendor.js:20730:34) at http://localhost:8100/build/vendor.js:20731:46 at Array.forEach (<anonymous>) at DeepLinker.getSegmentsFromNav (http://localhost:8100/build/vendor.js:20730:34)
Stack
Error: Uncaught (in promise): TypeError: navContainer.parent.getAllChildNavs is not a function
TypeError: navContainer.parent.getAllChildNavs is not a function
    at UrlSerializer._createSegment (http://localhost:8100/build/vendor.js:42606:81)
    at UrlSerializer.serializeComponent (http://localhost:8100/build/vendor.js:42569:29)
    at DeepLinker.getSegmentFromNav (http://localhost:8100/build/vendor.js:20749:33)
    at DeepLinker.getSegmentsFromNav (http://localhost:8100/build/vendor.js:20725:32)
    at http://localhost:8100/build/vendor.js:20731:46
    at Array.forEach (<anonymous>)
    at DeepLinker.getSegmentsFromNav (http://localhost:8100/build/vendor.js:20730:34)
    at http://localhost:8100/build/vendor.js:20731:46
    at Array.forEach (<anonymous>)
    at DeepLinker.getSegmentsFromNav (http://localhost:8100/build/vendor.js:20730:34)
    at c (http://localhost:8100/build/polyfills.js:3:13535)
    at Object.reject (http://localhost:8100/build/polyfills.js:3:12891)
    at SuperTab.NavControllerBase._fireError (http://localhost:8100/build/vendor.js:43386:16)
    at SuperTab.NavControllerBase._failed (http://localhost:8100/build/vendor.js:43374:14)
    at http://localhost:8100/build/vendor.js:43429:59
    at t.invoke (http://localhost:8100/build/polyfills.js:3:9283)
    at Object.onInvoke (http://localhost:8100/build/vendor.js:4508:37)
    at t.invoke (http://localhost:8100/build/polyfills.js:3:9223)
    at r.run (http://localhost:8100/build/polyfills.js:3:4452)
    at http://localhost:8100/build/polyfills.js:3:14076

**Comment by ihadeed** [comment]
Updated the repo recently. Clone it again and it should work well.
